### DISCUSSION TITLE
Node-Red Addon Settings File differences

### DISCUSSION THREAD

**Discussion by pmendiuk** [hassio-addons/addon-node-red#1121] [Q&A]
I am trying to get node-red-contrib-homeseer Device Node to work in the Node-Red addon.  The node uses web hooks for device status changes etc.  The node does not support user/password and works correctly with a stand alone instance of Node-Red with the default settings.js but does not work with the add-on.  Here is one of the repeating entries in the add-on log:

`2021/09/24 15:22:03 [error] 507#507: *4958548 auth request unexpected status: 500 while sending to client, client: 192.168.1.12, server: aXX7b954-nodered, request: "POST /homeseer/webhook HTTP/1.1", host: "192.168.1.126:1880"`

The add-on configurations is:

```
credential_secret: XXXX
theme: default
http_node:
  username: ''
  password: ''
http_static:
  username: ''
  password: ''
ssl: false
certfile: fullchain.pem
keyfile: privkey.pem
system_packages: []
npm_packages: []
init_commands: []
```

In the settings.js file I see the note about the configuration keys that are controlled by the add-on.
```
/**
 * PLEASE NOTE! IMPORTANT! READ!
 *
 * This is a modified version of the settings file. Some parts of the
 * settings are actually controlled by the Home Assistant add-on.
 *
 * Parts that are handled by it, are removed from this settings template.
 * The following configuration keys are controlled by the add-on and removed.
 *
 * - uiPort (port setting in the add-on log)
 * - uiHost (no need to manually configure this in the add-on)
 * - debugUseColors (disabled, won't work in the add-on)
 * - flowFile (fixed to flows.json)
 * - credentialSecret (credentials_secret in the add-on configuration)
 * - userDir (is set fixed to `/config/node-red`)
 * - nodesDir (is set fixed to `/config/node-red/nodes`)
 * - adminAuth (known as users in the add-on configuration)
 * - https (ssl settings in the add-on configuration)
 * - logging.console.level (log_level in the add-on configuration)
 * - httpNodeAuth (http_node settings in the add-on configuration)
 * - httpStaticAuth (http_static settings in the add-on configuration)
 * - httpNodeRoot (set fixed to `/endpoint` )
 *
 * If you like to change those settings, some are available via the add-on
 * settings/option in the Supervisor panel in Home Assistant.
 */
```
Is there any other places this could be set or configured?
