### ISSUE TITLE
Unable to serve static content

### ISSUE THREAD

**Issue by jdesai61** [hassio-addons/addon-node-red#1068]
# Problem/Motivation

I am trying to use some static fonts in my node-red GUI but unable to server them using httpStatic functionality of node-red add-on. This functionality works when I run node-red container in a separate VM .

## Expected behavior

NOTES:
```
My http_static config has a username/password.
In /config/node-red/settings.js I have specified httpStatic:  /config/node-red/myfiles
In /config/node-red/myfiles   there are several files including readme.txt
```

I expect http://myip:1880/readme.txt   to serve static content (readme.txt) under directory specified for httpStatic in settings.js, However, when I tried to access the above I keep getting repeated password prompts. Tested using Edge and Chrome.

## Actual behavior

I keep getting repeated password prompts despite repeatedly entering correct username and password. 

## Steps to reproduce

Setup http_static and httpStatic as shown above and try to access http://yourip:1880/myfiles/readme.txt

My config:
```
credential_secret: Secret
theme: default
http_node:
  username: Dad
  password: MyPassword
http_static:
  username: Dad
  password: MyPassword
ssl: false
certfile: fullchain.pem
keyfile: privkey.pem
require_ssl: false
system_packages: []
npm_packages: []
init_commands: []

```
My /config/node-red/settings.js file entry:
`httpStatic: '/config/node-red/myfiles',`

When I login to node-red add-on shell( using Portainer), the /var/log/nginx/error.log file has zero length.
