### ISSUE TITLE
"413 Request Entity Too Large" error when deploying modified flow

### ISSUE THREAD

**Issue by b3nj1** [hassio-addons/addon-node-red#1175]
# Problem/Motivation

With version 10.1.0 of the add-on, I get a "413 Request Entity Too Large" error when trying to deploy modified flows. Any modification causes this including just moving a node. This was not a problem in 10.0.1.

## Expected behavior

Be able to handle updating flows.

## Actual behavior

<img width="1006" alt="image" src="https://user-images.githubusercontent.com/13173423/141491621-ba74babc-a30a-44ba-b0a2-cded0d6e76be.png">

## Steps to reproduce

I'm not sure it is unique to my setup. I make heavy use of node-red, so my flows json file is probably on the large size at 1.4MB. I don't know if that file size is related to this issue, but thought I'd mention it.

## Proposed changes

 I wish I had a proposal. I looked at the settings.js and other reports of issues with node-red hitting 413 errors. Some have pointed to this commented-out setting:
https://github.com/hassio-addons/addon-node-red/blob/2bbc8e2043ea555f63e6852f4524cc8813e1f93a/node-red/rootfs/etc/node-red/settings.js#L90

However, if the default is really 5m and the data being pushed is an updated flows.json (mine being 1.4m), this shouldn't be a problem.

**Comment by b3nj1** [comment]
I should have noticed the nginx in the error as a clue. I switched to the nginx proxy yesterday. If I connect locally, I don't have this problem.

Closing the issue.

**Comment by b3nj1** [comment]
And... if it helps anyone else, I was able to reconfigure the nginx add-on to allow large node-red flow updates.

### Add-on config
Set customize.active to true:
```
domain: myhost.duckdns.org
certfile: fullchain.pem
keyfile: privkey.pem
hsts: max-age=31536000; includeSubDomains
cloudflare: false
customize:
  active: true
  default: nginx_proxy_default*.conf
  servers: nginx_proxy/*.conf
```

### Custom conf file
Create a custom /share/nginx_proxy_default_*.conf file with the following (adjust 100M to your needs). I called my file /share/nginx_proxy_default_client_max_body_size.conf. 
`client_max_body_size 100M;
`
