### ISSUE TITLE
Issue when ESPHome creates 2 entites on on econtroller -> both will be called when I want only one

### ISSUE THREAD

**Issue by ptC7H12** [hassio-addons/addon-node-red#1586]
Hey, 
I've go stumbled over an issue in this addon.

I've got an ESPHome Controller on which I've got 2 Outputs. Both are lights, one is monochromatic and the other is RGB.
```
light:
#Flur_klein
  - platform: monochromatic
    output: gpio_15_White
    name: "Weiß_WW"
   
  - platform: neopixelbus
    variant: WS2812
    pin: GPIO2
    num_leds: 16
    type: RGB
    name: "RBG_WW"
```

When I create a Flow in Node-Red with "Call Service"
![image](https://user-images.githubusercontent.com/4460900/229899172-ddce1a7f-0c9e-4177-abac-3353b3463ae0.png)

And when the flow is triggered, then both the "Weiß_WW" and "RGB_WW" are turned on. It doesn't matter which one I choose.

One example: When I call service "turn_on" on the entity "RGB_WW" both are turned on and afterwards I'm calling the service "turn_off" for entity "Weiß_WW" both are turned off.
You can see this in the debug Information:
```
4.4.2023, 21:28:09cc793c95c086e8d3
sent data : msg :
object
domain: "light"
service: "turn_on"
data: object
brightness_pct: 100
area_id: "wohnzimmer"
device_id: "a182e99bc029413eb495364fe945d9c0"
entity_id: "light.rbg_ww"

4.4.2023, 21:28:56f87148d94a093aac
sent data : msg :
object
domain: "light"
service: "turn_off"
data: object
area_id: "wohnzimmer"
device_id: "a182e99bc029413eb495364fe945d9c0"
entity_id: "light.weiss_ww"
```

When I try the same via Home Assistant automations, all works perfectly!

Can you please have a look into this? I don't want to do some Automation in HA and some in NR
