### ISSUE TITLE
NR4: Flow Properties missing (double-click on tab)

### ISSUE THREAD

**Issue by SynoUser-NL** [hassio-addons/addon-node-red#1906]
# Problem/Motivation

When trying to edit the name of one of my Flow tabs in NR4 in my Home Assistant installation, a properties section is missing:
![image](https://github.com/hassio-addons/addon-node-red/assets/10847240/1ada1519-83e7-4557-9593-d2c330f96777)

Whereas in a local installation of NR4 this is the same is in the previous version (3.10).

## Expected behavior

The properties of the Flow Edit should be visible, which allows the name change.

![image](https://github.com/hassio-addons/addon-node-red/assets/10847240/13151320-bd26-443d-b369-f98c2a79f27b)

## Steps to reproduce

In the latest version of the add-on NodeRED for HA, version 4, double click on a Flow (tab) name. 
The properties of the Flow do not display.

## Proposed changes

Well.. make it work again. :)

**Comment by 3ative** [comment]
Unable to reproduce here, worked on 18.0.1 just installed 18.0.2 still fine
![image](https://github.com/hassio-addons/addon-node-red/assets/51385971/4711bb1f-0b83-4ac8-a1ea-8f1f0a79d2d3)

**Comment by 3ative** [comment]
From Log:
```yaml
 Add-on version: 18.0.2
 You are running the latest version of this add-on.
 System: Home Assistant OS 12.4  (amd64 / qemux86-64)
 Home Assistant Core: 2024.6.4
 Home Assistant Supervisor: 2024.06.2
 ```
