### ISSUE TITLE
Prompting for password when loading files from www

### ISSUE THREAD

**Issue by nospam2k** [hassio-addons/addon-node-red#2039]
I have set the usernames and passwords for http_static and http_node to "" in configuration, and I have set httpStatic to /config/www in settings.js, but I'm getting a prompt for a username and password.

**Comment by sinclairpaul** [comment]
Please ensure you have followed the documentation.

**Comment by nospam2k** [comment]
I used: 
```
theme: dark
http_node:
  username: ""
  password: ""
http_static:
  username: ""
  password: ""
ssl: false
certfile: daford.work.cert.pem
keyfile: daford.work.privkey.pem
system_packages: []
npm_packages:
  - better-sqlite3
init_commands: []
credential_secret: xxxxxxxxx
leave_front_door_open: false
```

But it is still promoting for a password.
