### ISSUE TITLE
NPM Error and failed startup

### ISSUE THREAD

**Issue by ghost** [hassio-addons/addon-node-red#662]
# Problem/Motivation

> With 7.1 I get an NPM Error and Node-RED doesn't start.

```
[13:00:33] INFO: Starting Node-RED...
> addon-node-red@ start /opt
> node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"
22 Aug 13:00:34 - [info] 
Welcome to Node-RED
===================
22 Aug 13:00:34 - [info] Node-RED version: v1.1.3
22 Aug 13:00:34 - [info] Node.js  version: v12.18.3
22 Aug 13:00:34 - [info] Linux 5.4.56 x64 LE
22 Aug 13:00:34 - [info] Loading palette nodes
22 Aug 13:00:39 - [info] Dashboard version 2.23.2 started at /endpoint/ui
/bin/sh: /opt/node_modules/node-red-node-pi-gpio/testgpio.py: not found
22 Aug 13:00:39 - [warn] rpi-gpio : Raspberry Pi specific node set inactive
22 Aug 13:00:39 - [info] Settings file  : /etc/node-red/config.js
22 Aug 13:00:39 - [info] Context store  : 'default' [module=memory]
22 Aug 13:00:39 - [info] User directory : /config/node-red/
22 Aug 13:00:39 - [warn] Projects disabled : editorTheme.projects.enabled=false
22 Aug 13:00:39 - [info] Flows file     : /config/node-red/flows.json
22 Aug 13:00:39 - [info] Server now running at http://127.0.0.1:46836/
22 Aug 13:00:39 - [info] Starting flows
22 Aug 13:00:40 - [info] Started flows
22 Aug 13:00:40 - [red] Uncaught Exception:
22 Aug 13:00:40 - TypeError: cb.apply is not a function
    at /config/node-red/node_modules/npm/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqCallback.oncomplete (fs.js:169:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! addon-node-red@ start: `node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the addon-node-red@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-08-22T11_00_41_024Z-debug.log
```

This is my config:

```
credential_secret: 'secret'
dark_mode: true
http_node:
  username: ''
  password: ''
http_static:
  username: ''
  password: ''
ssl: true
certfile: fullchain.pem
keyfile: privkey.pem
require_ssl: true
system_packages:
  - build-base
  - g++
  - cairo-dev
  - jpeg-dev
  - pango-dev
  - imagemagick
npm_packages:
  - fs-minipass
  - minizlib
  - color-thief-node
init_commands: []
```

The versions:
```
 Add-on version: 7.1.0
 You are running the latest version of this add-on.
 System: HassOS 4.12  (amd64 / qemux86-64)
 Home Assistant Core: 0.114.3
 Home Assistant Supervisor: 235
```

## Steps to reproduce

> I think there is a bootloop due to that error.
