### ISSUE TITLE
RFX nodes no longer work in version 8.0.0

### ISSUE THREAD

**Issue by DaGolle** [hassio-addons/addon-node-red#861]
# Problem/Motivation

> RFX nodes no longer work in version 8.0.0

## Expected behavior

> RFX nodes are available without additional configuration

## Actual behavior

> RFX nodes are NOT available, not even with additional packages added (see also https://community.home-assistant.io/t/node-red-contrib-rfxcom-stopped-working/212598, however, the solution proposed here does not seem to work in v 8.0.0)

## Steps to reproduce

> Upgrade to version 8.0.0 and try to add an RXF node

my configuration for Node-RED add-on:
```
credential_secret: '!secret node_red_secret'
dark_mode: false
http_node:
  username: ''
  password: ''
http_static:
  username: ''
  password: ''
ssl: false
certfile: fullchain.pem
keyfile: privkey.pem
require_ssl: false
system_packages: []
npm_packages:
  - node-red-contrib-httpauth
init_commands: []
```

## Proposed changes

> Workaround, for me, was to go back to Node-RED add-on version 7.2.11
