### ISSUE TITLE
node red addon is missing in Home Assistant Community Add-ons

### ISSUE THREAD

**Issue by tiger-seo** [hassio-addons/addon-node-red#897]
# Problem/Motivation

node red addon is missing, so cant be installed

## Expected behavior

node red addon is available in Home Assistant Community Add-ons

## Actual behavior

node red addon is missing in Home Assistant Community Add-ons

## Steps to reproduce

open Add-on Store
try to find Node Red in Home Assistant Community Add-ons

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Please list the installed repostories in the add-on store.

**Comment by tiger-seo** [comment]
i think it may be related to the fact that my local supervisor version is  2021.01.7  ( not Supervisor 2021.02.6 )

**Comment by tiger-seo** [comment]
or maybe it is also related to following actions:  i did update of node red addon, i did update of supervisor,  then i've got a problem with supervisor 2021.02.6 , so i did downgrade of supervisor from 2021.02.6 to 2021.01.7,  afterwards all addons are disappeared , so i have to reinstall them from addon store - everything except node-red, because it was missing

**Comment by tiger-seo** [comment]
```
repositories:
- maintainer: you
  name: Local add-ons
  slug: local
  source: local
  url: https://home-assistant.io/hassio
- maintainer: ESPHome <contact@esphome.io>
  name: ESPHome Home Assistant Add-Ons
  slug: 15ef4d2f
  source: https://github.com/esphome/hassio
  url: https://github.com/esphome/hassio
- maintainer: Daniel Welch <dwelch2102@gmail.com>
  name: 'Home Assistant Add-on: Zigbee2mqtt'
  slug: 7ad98f9c
  source: https://github.com/danielwelch/hassio-zigbee2mqtt
  url: https://www.zigbee2mqtt.io
- maintainer: Stephen Beechen <stephen@beechens.com>
  name: Home Assistant Google Drive Backup Repository
  slug: cebe7a76
  source: https://github.com/sabeechen/hassio-google-drive-backup
  url: https://github.com/sabeechen/hassio-google-drive-backup
- maintainer: Home Assistant
  name: Official add-ons
  slug: core
  source: core
  url: https://home-assistant.io/addons
- maintainer: Franck Nijhof <frenck@addons.community>
  name: Home Assistant Community Add-ons
  slug: a0d7b954
  source: https://github.com/hassio-addons/repository
  url: https://addons.community
```
